
resources:
  - name: demo
    type: git
    source:
      uri: https://github.com/demo151996/demo.git
      branch: main

  - name: jdk21-image
    type: registry-image
    source:
      repository: ghcr.io/demo151996/jdk21-custom
      tag: latest
      username: CarolineMarshel
      password: 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
